version: '3.8'

services:
  fivedollarbnb-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fivedollarbnb
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_BSC_RPC=https://bsc-dataseed.binance.org/
      - NEXT_PUBLIC_RPC_URL=https://bsc-dataseed.binance.org/
      - NEXT_PUBLIC_SUBGRAPH_URL=http://86.107.77.113:8000/subgraphs/name/ridebnb
      - NEXT_PUBLIC_CONTRACT_ADDRESS=0xd4894bfF2096Ad0bB4D2815d57b5C21E2E16db44
      - NEXT_PUBLIC_CHAIN_ID=56
      - NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID=85bbe92e974bca9f67c7910e0d1365ea
      - NEXT_PUBLIC_DEFAULT_REFER=36999
    restart: unless-stopped
    networks:
      - fivedollarbnb-network

networks:
  fivedollarbnb-network:
    driver: bridge
